%YAML:1.0
camera:
    index: 1
    type: 'OCAM'
    resolution:
        width: 640
        height: 480
    camera_matrix: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [414.664073, 0.000000, 327.848765, 0.000000, 414.664073, 242.006555, 0.000000, 0.000000, 1.000000]
    distortion_vector: !!opencv-matrix
        rows: 5
        cols: 1
        dt: d
        data: [-0.224108, 0.068924, -0.001305, -0.000329, -0.012663]
    ground_plane: !!opencv-matrix
        rows: 1
        cols: 4
        dt: d
        data: [0.000000, 0.000000, 1.000000, -2.456176]
    external_transformation: !!opencv-matrix
        rows: 4
        cols: 4
        dt: d
        data: [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.]

communicator:
    interface: 'wlan0'
    group: 'EAGLE'
    zyre_port: 5670
    zyre_wait_time: 100

calibrator:
    images_path: '/home/ruben/Documents/Work/Repositories/ProjectEagle/eagle/config/calibration'
    pattern: 'CHESSBOARD'
    board_width: 6
    board_height: 7
    square_size: 0.108
    calib_fix_aspect_ratio: 1

detector:
    blob:
        minThreshold: 10
        maxThreshold: 200
        filterByArea: 1
        minArea: 80
        filterByCircularity: 1
        minCircularity: 0.85
    min_robot_area: 0.06
    min_obstacle_area: 0.02
    markers:
        triangle_ratio: 0.625
        qr_posx: 0
        qr_posy: 0
        qr_sizex: 0.8
        qr_sizey: 0.8
        qr_nbitx: 2
        qr_nbity: 2
    thresholds:
        bg_subtraction: 24
        top_marker: 0.1
        triangle_ratio: 0.1
    background_path: '/home/ruben/Documents/Work/Repositories/ProjectEagle/eagle/config/background.png'
