#ifndef EXAMPLES_CONFIG_H
#define EXAMPLES_CONFIG_H

#define EXAMPLE_CAMERA_T LatitudeCamera
#define EXAMPLE_CAMERA_INDEX 0
#define EXAMPLE_CAMERA_CALIBRATION "../config/see3cam.yml"
//#define EXAMPLE_COMMUNICATOR_INTERFACE "enp0s25"
#define EXAMPLE_COMMUNICATOR_INTERFACE "wlp12s0"

#endif //EXAMPLES_CONFIG_H
